# file      : tests/compiler/cxx-indenter/buildfile
# copyright : Copyright (c) 2009-2013 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libcutl%lib{cutl}

exe{driver}: cxx{driver} $libs
exe{driver}: test.output = output.std
