# file      : tests/buildfile
# copyright : Copyright (c) 2009-2013 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

d = compiler/ container/ fs/ re/ shared-ptr/
./: $d
include $d
