# file      : tests/compiler/traversal/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libcutl%lib{cutl}

exe{driver}: {hxx cxx}{*} $libs
exe{driver}: test.output = output.std
