# file      : tests/re/buildfile
# copyright : Copyright (c) 2009-2019 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libcutl%lib{cutl}

exe{driver}: {hxx cxx}{*} $libs
